sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Md1+9If3yEWvcPONKZY/RS4jsoZFHuvV3Ru4Y3xHtSAoYALYURzO5Xv7iby6i1bfY5LCIpBUxujduBALan2CUStRVXqMWGkzY4WB+Ia5iOLcej3w6R9hv+t4SWJkDTjRrm3fFGEX5HF/g5AJYMOk6GoL27de+CQiAXfnzsUbVsBbrdC68ILt7F83Ws5DwF/VIvuhzAAp9Sz13FleD9FZFkzJQv5Ln98mkBa3y8rQAuvdFF0WzveWAaf/yYUGXNZNUrlJab10aDGfJ3EZIAPaXkHWoGcgU1M2UlhhXNmkTf8BTdH+2urUO8e8tLlxsH169O8AhWtwkRuBgQE0pFKJBJBK4vGtaYhm4Uiv7lzVHrlCU+Tf6cSSvgmv8aJvaZD2NLOPP80L9U2UMfa4rxxaQEV42kRE1LFxzG1GD4xfTOa0hCdtyNAZdSZY+RewqSfoa0fAWS3c6LJtaUxhh4PimLbY5BZ0ehHbDzfrYPPFf8xeHE1dUEMSDld+N8xO6TB/asNpZMjifN5Rf48fZQ5O5xUZHDZB/O7rbDyqUNmpWxy7NUyGaY+s2/8lj8fMMoCwU1PWBDq/L2BHNL7ippZeBQtXOx8WIf4f9sQfZ5CzNw9tkqRhraiv+aRoV2zq9wQGtQEw85rRc2QPC8N7umQG9px/rqRBub43yDzpg54f51Q=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Trimmed-Lamp-and-other-Stories-of-the-Four-Million_3707
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy